MvcBlogProje/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProje.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        AboutManager abm = new AboutManager();
        public ActionResult Index()
        {
            var aboutcontent = abm.GetAll();
            return View(aboutcontent);
        }
        public PartialViewResult Footer()
        {
            var aboutcontentlist1 = abm.GetAll();
            return PartialView(aboutcontentlist1);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager autman = new AuthorManager();
            var authorlist = autman.GetAll();
            return PartialView(authorlist);
        }
    }
}

MvcBlogProje/Controllers/AuthorController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProje.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author

        BlogManager blogmanager = new BlogManager();
        AuthorManager authormanager = new AuthorManager();
        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = blogmanager.GetBlogByID(id); 
            return PartialView(authordetail);
        }
        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogauthorid = blogmanager.GetAll().Where(x => x.BlogID == id).Select(y => y.AuthorID).FirstOrDefault();
            var authorblogs = blogmanager.GetBlogByAuthor(blogauthorid);

            return PartialView(authorblogs);
        }
        public ActionResult AuthorList()
        {
           var authorlist =  authormanager.GetAll();
            return View(authorlist);
        }
        [HttpGet]
        public ActionResult AddAuthor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAuthor(Author p)
        {
            authormanager.AddAuthorBL(p);
            return RedirectToAction("AuthorList");
        }
        [HttpGet]
        public ActionResult AuthorEdit(int id)
        {
            Author author = authormanager.FindAuthor(id);
            return View(author);
        }
        [HttpPost]
        public ActionResult AuthorEdit(Author p)
        {
            authormanager.EditAuthor(p);
            return RedirectToAction("AuthorList");
        }

    }
}

MvcBlogProje/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using DataAccsessLayer.Concrete;
using EntityLayer.Concrete;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace MvcBlogProje.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        BlogManager bm = new BlogManager();
      
            
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult BlogList(int page = 1)
        {
            var bloglist = bm.GetAll().ToPagedList(page, 6);
            return PartialView(bloglist);
        }
        public PartialViewResult FeaturedPosts()
        {
            var posttitle1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.posttitle1 = posttitle1;
            ViewBag.postimage1 = postimage1;
            ViewBag.blogdate1 = blogdate1;

            var posttitle2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimage2 = postimage2;
            ViewBag.blogdate2 = blogdate2;

            var posttitle3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimage3 = postimage3;
            ViewBag.blogdate3 = blogdate3;

            var posttitle4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate4= bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimage4 = postimage4;
            ViewBag.blogdate4 = blogdate4;

            var posttitle5 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage5 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate5  = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogDate).FirstOrDefault();

            ViewBag.posttitle5 = posttitle5;
            ViewBag.postimage5 = postimage5;
            ViewBag.blogdate5 = blogdate5;



            return PartialView();
        }

        public PartialViewResult OtherFeaturedPosts()
        {
            return PartialView();
        }
        //public PartialViewResult MailSubscribe()
        //{
        //    return PartialView();
        //}
        public ActionResult BlogDetails()
        {
            return View();
        }
        public PartialViewResult BlogCover(int id)
        {
            var BlogDetailList = bm.GetBlogByID(id);
            return PartialView(BlogDetailList);
        }
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailList = bm.GetBlogByID(id);
            return PartialView(BlogDetailList);
        }
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = bm.GetBlogByCategory(id);
            var CategoryName = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
            ViewBag.CategoryName = CategoryName;
            var CategoryDesc = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.CategoryDesc = CategoryDesc;
            return View(BlogListByCategory);
        }

        public ActionResult AdminBlogList()
        {
            var bloglist = bm.GetAll();
            return View(bloglist); 
        }
        [HttpGet]
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from x in c.Authors.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AuthorName,
                                               Value = x.AuthorID.ToString()
                                           }).ToList();
            ViewBag.values2 = values2;
            return View();
        }
        [HttpPost]
        public ActionResult AddNewBlog(Blog b)
        {
            bm.BlogAddBL(b);
            return RedirectToAction("AdminBlogList");
        }
        public ActionResult DeleteBlog(int id)
        {
            bm.DeleteBlogBL(id);
            return RedirectToAction("AdminBlogList");
        }
        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {
            Blog blog = bm.FindBlog(id);
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from x in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorName,
                                                Value = x.AuthorID.ToString()
                                            }).ToList();
            ViewBag.values2 = values2;
            return View(blog);
        }
        [HttpPost]
        public ActionResult UpdateBlog(Blog p)
        {
            bm.UpdateBlog(p);
            return RedirectToAction("AdminBlogList");

        }
        public ActionResult GetCommentByBlog(int id)
        {
            CommentManager cm = new CommentManager();
            var commentList = cm.CommentByBlog(id);
            return View(commentList);
        }
    }
}

MvcBlogProje/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProje.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category

        CategoryManager cm = new CategoryManager();
        public ActionResult Index()
        {
            var categoryvalues = cm.GetAll();
            return View(categoryvalues);
        }
        public PartialViewResult BlogDetailsCategoryList()
        {
            var categoryvalues = cm.GetAll();
            return PartialView(categoryvalues);
        }

    }
}

MvcBlogProje/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProje.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment

        CommentManager cm = new CommentManager();
        public PartialViewResult CommentList(int id)
        {
            var commentList = cm.CommentByBlog(id);
            return PartialView(commentList);
        }
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult LeaveComment(Comment c)
        {
            cm.CommentAdd(c);
            return PartialView();
        }
        public ActionResult AdminCommentList()
        {
            var commentlist = cm.CommentList(); 
            return View(commentlist);
        }
    }
}

MvcBlogProje/Views/Blog/AddNewBlog.cshtml
@model EntityLayer.Concrete.Blog

@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })
    <br />
    @Html.Label("Resim Yolu")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.values2, new { @class = "form-control" })
    <br />
    @Html.Label("içerik")
    @Html.TextAreaFor(x => x.BlogContent, 5, 20, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">KAYDET</button>

</form>

MvcBlogProje/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Blog Listesi</h2>
<br/>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kategori</th>
        <th>Başlık</th>
        <th>Tarih</th>
        <th>Güncelle</th>
        <th>Sil</th>
        <th>Detaylar</th>
        <th>Yorumlar</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.BlogID</td>
                    <td>@item.Category.CategoryName </td>
                    <td>@item.BlogTitle</td>
                    <td>@item.BlogDate.ToShortDateString()</td>
                    <td><a href="/Blog/UpdateBlog/@item.BlogID" class="btn btn-danger">Güncelle</a></td>
                    <td><a href="/Blog/DeleteBlog/@item.BlogID" class="btn btn-success">Sil</a></td>
                    <td><a href="" class="btn btn-warning">Detaylar</a></td>
                    <td><a href="/Blog/GetCommentByBlog/@item.BlogID" class="btn btn-dark">Yorumlar</a></td>
                </tr>
            }

 </table>
<a href="/Blog/AddNewBlog/" class="btn btn-primary">Yeni Blog Ekle</a>

MvcBlogProje/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Kategori</span>
                <h3>@ViewBag.CategoryName</h3>
                <p>@ViewBag.CategoryDesc</p>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
            <div class="col-lg-4 mb-4">
                <div class="entry2">
                    <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage" alt="Image" sytle="height:250px" class="img-fluid rounded"></a>
                    <div class="excerpt">
                        <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                        <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                        <div class="post-meta align-items-center text-left clearfix">
                            <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorName</a></span>
                            <span>&nbsp;-&nbsp;@(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                        </div>

                        <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(""))...</p>
                        <p><a href="#">Read More</a></p>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>
@Html.Action("Footer", "About")

MvcBlogProje/Views/Blog/BlogCover.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{

    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage');">
        <div class="container">
            <div class="row same-height justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="post-entry text-center">
                        <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                        <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                        <div class="post-meta align-items-center text-center">
                            <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                            <span>&nbsp;-&nbsp; 30 Mart 2023</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MvcBlogProje/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")


<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">

                @Html.Action("BlogReadAll", "Blog")

                @Html.Action("CommentList", "Comment")

            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")

                @Html.Action("AuthorPopularPost", "Author")

                @Html.Action("BlogDetailsCategoryList", "Category")
            </div>
        </div>
    </div>
</section>
@*@Html.Action("OtherFeaturedPosts", "Blog")*@

@Html.Action("AddMail", "Mailsubscribe")

@Html.Action("Footer", "About")

MvcBlogProje/Views/Blog/BlogList.cshtml
@using PagedList
@using PagedList.Mvc

@model IEnumerable<EntityLayer.Concrete.Blog>


@{string color = "";}

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <h2>Blog Listesi</h2>
            </div>
        </div>
        <div class="row">
            @foreach (var x in Model)
            {
                if (x.Category.CategoryName == "Seyahat")
                {
                    color = "post-category text-white bg-success mb-3";
                }
                if (x.Category.CategoryName == "film&dizi")
                {
                    color = "post-category text-white bg-danger mb-3";
                }
                if (x.Category.CategoryName == "Yazılım")
                {
                    color = "post-category text-white bg-warning mb-3";
                }
                if (x.Category.CategoryName == "Teknoloji")
                {
                    color = "post-category text-white bg-secondary mb-3";
                }
                if (x.Category.CategoryName == "kültür&sanat")
                {
                    color = "post-category text-white bg-info mb-3";
                }

                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="single.html"><img src="@x.BlogImage " sytle="height:250px" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="@color">@x.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@x.BlogID">@x.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@x.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1">By <a href="#">@x.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @(((DateTime)x.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            </div>

                            <p>@x.BlogContent.Substring(0, x.BlogContent.Substring(0, 200).LastIndexOf(""))...</p>
                            <p><a href="#">Devamını Oku...</a></p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new {page}))

MvcBlogProje/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{



    <div class="post-content-body">
        <p>@item.BlogContent .</p>
        <div class="row mb-5 mt-5">
            <div class="col-md-12 mb-4">
                <img src="@item.BlogImage" alt="Image placeholder" class="img-fluid rounded">
            </div>
        </div> </div>
}

MvcBlogProje/Views/Blog/FeaturedPosts.cshtml
<div class="site-section bg-light">
    <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <div class="col-md-4">
                <a href="single.html" class="h-entry mb-30 v-height gradient" style="background-image: url('@ViewBag.postimage1');">
                    <div class="text">
                        <h2>@ViewBag.posttitle1</h2>
                        <span class="date">July 19, 2019</span>
                    </div>
                </a>
                <a href="single.html" class="h-entry v-height gradient" style="background-image: url('@ViewBag.postimage2');">

                    <div class="text">
                        <h2>@ViewBag.posttitle2</h2>
                        <span class="date">19 Şubat 2023</span>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="single.html" class="h-entry img-5 h-100 gradient" style="background-image: url('/miniblog/images/img_v_1.jpg');">

                    <div class="text">
                    <h2>@ViewBag.posttitle5</h2>
                        <span class="date">27 Mart 2023</span>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="single.html" class="h-entry mb-30 v-height gradient" style="background-image: url('@ViewBag.postimage3');">

                    <div class="text">
                        <h2>@ViewBag.posttitle3</h2>
                        <span class="date">July 19, 2019</span>
                    </div>
                </a>
                <a href="single.html" class="h-entry v-height gradient" style="background-image: url('@ViewBag.postimage4');">

                    <div class="text">
                        <h2>@ViewBag.posttitle4</h2>
                        <span class="date">20 Haziran 2023</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

MvcBlogProje/Views/Blog/GetCommentByBlog.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>
@{
    ViewBag.Title = "GetCommentByBlog";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>YORUMLAR</h2>
<br/>
<table class="table table-bordered">
    <tr>
        <th>Kullanıcı</th>
        <th>Yorum</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.UserName </td>
                    <td>@item.CommentText</td>
                </tr>
            }

</table>

MvcBlogProje/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("FeaturedPosts", "Blog")

@Html.Action("BlogList", "Blog")

@*@Html.Action("OtherFeaturedPosts", "Blog")*@

@Html.Action("AddMail", "Mailsubscribe")

@Html.Action("Footer", "About")

MvcBlogProje/Views/Blog/OtherFeaturedPosts.cshtml
<div class="site-section bg-light">
    <div class="container">

        <div class="row align-items-stretch retro-layout">

            <div class="col-md-5 order-md-2">
                <a href="single.html" class="hentry img-1 h-100 gradient" style="background-image: url('/miniblog/images/img_4.jpg');">
                    <span class="post-category text-white bg-danger">Travel</span>
                    <div class="text">
                        <h2>The 20 Biggest Fintech Companies In America 2019</h2>
                        <span>February 12, 2019</span>
                    </div>
                </a>
            </div>

            <div class="col-md-7">

                <a href="single.html" class="hentry img-2 v-height mb30 gradient" style="background-image: url('images/img_1.jpg');">
                    <span class="post-category text-white bg-success">Nature</span>
                    <div class="text text-sm">
                        <h2>The 20 Biggest Fintech Companies In America 2019</h2>
                        <span>February 12, 2019</span>
                    </div>
                </a>

                <div class="two-col d-block d-md-flex">
                    <a href="single.html" class="hentry v-height img-2 gradient" style="background-image: url('/miniblog/images/img_2.jpg');">
                        <span class="post-category text-white bg-primary">Sports</span>
                        <div class="text text-sm">
                            <h2>The 20 Biggest Fintech Companies In America 2019</h2>
                            <span>February 12, 2019</span>
                        </div>
                    </a>
                    <a href="single.html" class="hentry v-height img-2 ml-auto gradient" style="background-image: url('/miniblog/images/img_3.jpg');">
                        <span class="post-category text-white bg-warning">Lifestyle</span>
                        <div class="text text-sm">
                            <h2>The 20 Biggest Fintech Companies In America 2019</h2>
                            <span>February 12, 2019</span>
                        </div>
                    </a>
                </div>

            </div>
        </div>

    </div>
</div>

MvcBlogProje/Views/Blog/UpdateBlog.cshtml
@model EntityLayer.Concrete.Blog

@{
    ViewBag.Title = "UpdateBlog";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.Label("Blog ID")
    @Html.TextBoxFor(x => x.BlogID, new { @class = "form-control" })

    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })
    <br />
    @Html.Label("Resim Yolu")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.values2, new { @class = "form-control" })
    <br />
    @Html.Label("içerik")
    @Html.TextAreaFor(x => x.BlogContent, 5, 20, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>

</form>